version: "3.9"

services:
  keycloak-service:
    image: quay.io/keycloak/keycloak:18.0.0
    container_name: keycloak-service
    environment:
      KEYCLOAK_IMPORT: realm-export.json
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
    ports:
      - "8082:8080"
    restart: on-failure
    command:
      - start-dev
    networks:
      - digital-media

  eureka-service:
    build: /eureka-service/.
    container_name: eureka-service
    ports:
      - "8761:8761"
    restart: on-failure
    networks:
      - digital-media

#  movies-service:
#    build: /movies-api/.
#    container_name: movies-service
#    ports:
#      - "8085:8085"
#    restart: on-failure
#    networks:
#      - digital-media

  bills-service:
    build: /bills-api/.
    container_name: bills-service
    ports:
      - "8086:8086"
    restart: on-failure
    networks:
      - digital-media
    depends_on:
      - eureka-service

networks:
  digital-media:
    name: digital-media