server:
  port: 8086

spring:
  application:
    name: bills-api
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/DigitalMedia
            token-uri: http://localhost:8082/realms/DigitalMedia/protocol/openid-connect/token
        registration:
          microservice:
            provider: keycloak
            client-id: microservice
            client-secret: vaeJYvgqBdUbodvUFiTs3fzCBranbQYs
            scope: openid
            #authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8086/
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
