server:
  port: 8085
spring:
  application:
    name: movies-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/moviesdb
  main:
    allow-circular-references: true
  security:
    client:
      provider:
        keycloak:
          issuer-uri: http://localhost:8082/realms/DigitalMedia
      registration:
        microservice:
          client-id: microservice
          client-secret: vaeJYvgqBdUbodvUFiTs3fzCBranbQYs
          scope: openid
          redirect_uri: http://localhost:8082/
app:
  cors:
    allowed-origins: http://localhost:3000

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true